"""
Django settings for after_sales_backend_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import datetime
import os
import sys
from pathlib import Path
from celery.schedules import timedelta, crontab


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&w@^7)35ww+cry_^n#y!tcivu@i5$6u%&^sz5(=y0h)5%ip&lo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'sales',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'after_sales_backend_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'after_sales_backend_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'after_sales',
    #     'USER': 'root',
    #     'PASSWORD': 'root',
    #     'PORT': 33061,
    #     'HOST': '127.0.0.1',
    # },
    'default': {
            'ENGINE': 'mssql',
            'NAME': 'after_sales',
            'USER': 'sa',
            'PASSWORD': 'Dev@4512',
            'HOST': '172.25.0.114',
            'PORT': '1433',  # 留空或设置为 SQL Server 的端口号，如果默认端口可留空
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',  # 根据你的 SQL Server 版本选择合适的驱动
                'TrustServerCertificate': 'yes',
                'MARS_Connection': True,  # 多活动结果集支持
            },
        },
    # OA正式系统数据库
    'sqlserver_oa_ecology9': {
        'ENGINE': 'mssql',
        'NAME': 'ecology9',
        'USER': 'sa',
        'PASSWORD': '2G#x0@hq)jaz~VpM',
        'HOST': '172.30.1.8',
        'PORT': '1433',  # 留空或设置为 SQL Server 的端口号，如果默认端口可留空
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # 根据你的 SQL Server 版本选择合适的驱动
            'MARS_Connection': True,  # 多活动结果集支持
        },
    },
    # 'DataBase': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'syncdb',
    #     'USER': 'root',
    #     'PASSWORD': 'Password123@doris',
    #     'PORT': 9030,
    #     'HOST': '172.24.0.19',
    # },
}

if os.getenv('DJANGO_USE_SQLITE') == '1':
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# 设置上传文件的目录和外部访问的路劲
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 缓存配置（用于存储溯源系统refresh_token）
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'trace-token-cache',
        'TIMEOUT': 60 * 60 * 24 * 30,  # 30天
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'sales.authentication.AfterSalesJWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/minute',  # 匿名用户每分钟100次
        'user': '1000/minute',  # 登录用户每分钟1000次
        'login': '5/minute',    # 登录接口每分钟5次
    },
    'EXCEPTION_HANDLER': 'sales.exceptions.custom_exception_handler',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}
#关闭允许所有ip访问
CORS_ALLOW_ALL_ORIGINS = False
#只允许以下IP访问接口
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://fw.yinglicloud.com',
]

TRACE_LOGIN_URL = os.getenv('TRACE_LOGIN_URL', 'http://172.25.1.29:8300/api/login/')
TRACE_REFRESH_URL = os.getenv('TRACE_REFRESH_URL', 'http://172.25.1.29:8300/token/refresh/')
TRACE_QUERY_URL = os.getenv('TRACE_QUERY_URL', 'http://172.25.1.29:8300/api/suyuan-query/?query_params=')
TRACE_LOGIN_USERNAME = os.getenv('TRACE_LOGIN_USERNAME', 'yladmim')  # 请替换为实际的溯源系统用户名
TRACE_LOGIN_PASSWORD = os.getenv('TRACE_LOGIN_PASSWORD', 'admin123456')  # 请替换为实际的溯源系统密码
TRACE_AUTH_SCHEME = os.getenv('TRACE_AUTH_SCHEME', 'JWTYF')
TRACE_HTTP_TIMEOUT = int(os.getenv('TRACE_HTTP_TIMEOUT', '60'))  # 增加到60秒，避免超时

# 企业微信配置
WECOM_CORP_ID = os.getenv('WECOM_CORP_ID', 'ww31a96ec54147e689')
# WECOM_CORP_SECRET = os.getenv('WECOM_CORP_SECRET', 'your_corp_secret_here')
WECOM_CORP_SECRET = os.getenv('WECOM_CORP_SECRET', 'KLcZY0UWNpx_rvZMr3XMmGNOpQ3aIQ5VOxFmXVFi2Hs')

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'error.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'sales': {
            'handlers': ['file', 'error_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}