# Generated by Django 4.2.7 on 2026-03-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(blank=True, max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_warranty', models.CharField(max_length=10)),
                ('issue_type', models.CharField(blank=True, max_length=100)),
                ('inverter_info', models.CharField(blank=True, max_length=200)),
                ('process_type', models.CharField(blank=True, max_length=100)),
                ('replace_serial_no', models.CharField(blank=True, max_length=100)),
                ('repair_details', models.JSONField(blank=True, default=dict)),
                ('repairer', models.CharField(blank=True, max_length=100)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
